name: Angular CI/CD to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./angular14   # 👈 go inside Angular project folder

      # Step 4: Build Angular app
      - name: Build Angular
        run: npm run build --prod
        working-directory: ./angular14   # 👈 same here

      # Step 5: Deploy to Azure WebApp
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "indrajithfirstazureapp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./angular14/dist/angular14   # 👈 update correct dist path
